## docker run -d --restart=unless-stopped -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker jenkins/jenkins:lts-centos /bin/bash
FROM jenkins/jenkins:lts-centos
USER root

