kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: demo
  namespace: ldx
  labels:
    k8s-app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: demo
  template:
    metadata:
      name: demo
      labels:
        k8s-app: demo
    spec:
      containers:
      - name: demo
        image: registry-vpc.cn-shenzhen.aliyuncs.com/lhs11/demo:24_1545477944470
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: JAVA_OPTS
          value: -Xms128m -Xmx2048m -Xss1m
        - name: SW_AGENT_NAME
          value: demo
        - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
          value: skywalking-oap-server.ldx:11800
        - name: SW_LOGGING_LEVEL
          value: ERROR
        resources:
          requests:
            cpu: '0'
            memory: 128Mi
          limits:
            memory: 2048Mi
        imagePullPolicy: Always
        securityContext:
          privileged: false
          procMount: Default
        readinessProbe:
          httpGet:
            path: /demo/services/local/system/user.japi
            port: 8080
            httpHeaders:
            - name: X-Probe-Header
              value: readinessProbe
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - mountPath: /logs
          name: logs-volume
      volumes:
      - name: logs-volume
        hostPath:
          path: /logs
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
      - name: ldx-registry-key
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
kind: Service
apiVersion: v1
metadata:
  name: demo
  namespace: ldx
  labels:
    k8s-app: demo
  annotations:
    traefik.ingress.kubernetes.io/session-cookie-name: "traefik-sticky"
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/circuit-breaker-expression: "NetworkErrorRatio() > 0.001"
    traefik.ingress.kubernetes.io/load-balancer-method: "drr"
spec:
  ports:
  - name: http
    protocol: TCP
    port: 9400
    targetPort: 8080
  selector:
    k8s-app: demo