version: '2'

services:
  jenkins:
    image: jenkins:2.182-centos
    container_name: jenkins 
    restart: always
    tty: true
    environment:
      TZ: Asia/Shanghai
    networks:
      - devops
    ports:
      - "30010:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /data:/data

networks:
  devops:
    external:
      name: devops01